---
- name: "Installation and Configuration"
  hosts: eap
  become: yes
  collections:
    - redhat.eap
  roles:
    - eap_install
    - eap_driver
    - eap_systemd
  vars:
    eap_home: "/opt/jboss_eap/jboss-eap-7.4/"
    eap_user: eap
    eap_group: eap
    eap_basedir_prefix: "/opt/jboss_eap"
    eap_port_range_offset: 100
    service_systemd_env_file: "/etc/eap.conf"
    service_systemd_conf_file: "/usr/lib/systemd/system/eap.service"
    eap_config_base: standalone-ha.xml
    eap_offline_install: True
    eap_apply_cp: True
    eap_version: "7.4.0"
    eap_patch_version: "7.4.7"
    eap_systemd_enable: True
    ansible_distribution: 'RedHat'
    eap_enable_yml_config: True
    eap_yml_configs: [ eap_ymlconfig.yml.j2 ]
    app:
      name: 'helloworld.war'
      url: 'https://drive.google.com/uc?export=download&id=16HOaSVF0bSYyjc8a8hkEiDlTqgJuGJfe'
  pre_tasks:
    - name: Enable and start the firewalld service
      become: yes
      ansible.builtin.systemd:
        name: firewalld
        enabled: yes
        state: started
    - name: "Configure firewall for EAP ports"
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: yes
      loop:
        - 8009/tcp
        - 8080/tcp
        - 9990/tcp
        - 7600/tcp
        - 7601/tcp
    - name: Create cluster node list
      ansible.builtin.set_fact:
        eap_cluster_nodes: >
          {{ eap_cluster_nodes | default([]) + [
               {
                 "name": item,
                 "address": 'jgroups-' + item,
                 "inventory_host": hostvars[item].ansible_default_ipv4.address | default(item) + '[7600]',
                 "value": hostvars[item].ansible_default_ipv4.address | default(item)
               }
             ] }}
      loop: "{{ ansible_play_batch }}"

  tasks:
    - name: Verify service is started
      ansible.builtin.service:
        name: eap
        state: started
      throttle: 1
    - name: Verify management port is accessible
      ansible.builtin.wait_for:
        port: 9990
        host: localhost
        connect_timeout: 3
        delay: 10
        timeout: 60
    - name: "Download demo app {{ app.name }} to deploy from {{ app.url }} into deployments"
      ansible.builtin.get_url:
        url: "{{ app.url }}"
        dest: "{{ eap_home }}/standalone/deployments/"
        owner: eap
        group: eap
        mode: 0644