---
- name: Upgrade EAP
  hosts: eap
  become: yes
  collections:
    - redhat.eap
  vars:
    eap_offline_install: True
    eap_apply_cp: True
    eap_version: "7.4.0"
    eap_patch_version: "7.4.9"
  roles:
    - role: eap_install
    - role: eap_systemd
  tasks:
    - name: Restart eap service
      ansible.builtin.service:
        name: eap
        state: restarted  
    - name: Verify management port is accessible
      ansible.builtin.wait_for:
        port: 9990
        host: localhost
        connect_timeout: 3
        delay: 10
        timeout: 60
